### ISSUE TITLE
Clarification of binder instructions.

### ISSUE THREAD

**Issue by fm75** [binder-examples/jupyterlab#3]
The README.md left a little too much to my imagination. I stumbled through and got it working on about my 3rd try. Then some experiments did not work - since I was just doing some trial and error and was not familiar with what binder needed.

- Is binder/postBuild necessary?
- Is the example binder/requirements.txt just needed for this repo, or is it some minimum for jupyterlab in binder?
- The reference to urlpath was unclear, or I did not get it. Originally I had a badge to copy, somehow, but it did not contain the query part which seems to be needed to start jupyterlab instead of a conventional notebook

**Comment by fm75** [comment]
I needed to find the [binder documentation](https://blog.jupyter.org/binder-2-0-a-tech-guide-2017-fd40515a3a84).  That pretty much answered my questions.

**Comment by choldgraf** [comment]
@fm75 I updated the README instructions - hope that's a bit more clear!

**Comment by fm75** [comment]
Thanks.

Sorry that I was too busy today to offer a PR

Fred
