### ISSUE TITLE
"Build Recommended" message at startup

### ISSUE THREAD

**Issue by YannickJadoul** [binder-examples/jupyterlab#5]
When starting this example on Binder (i.e., through the badge link, https://mybinder.org/v2/gh/binder-examples/jupyterlab/master?urlpath=lab/tree/index.ipynb), I get a pop-up from JupyterLab with the following message:

```
JupyterLab build is suggested:

jupyterlab-drawio needs to be included in build
@jupyterlab/geojson-extension needs to be included in build
```

I am getting a similar message in my own build, but then for the @jupyter-widgets/jupyterlab-manager extension. However, for https://github.com/jupyterlab/jupyterlab-demo, this seems to be working fine. Any idea on what could be wrong and how to fix it?

**Comment by choldgraf** [comment]
huh - that is quite strange! I wonder if this is because JupyterLab was recently updated. Are there any differences in the configuration files (e.g. environment.yml or requirements.txt) of the two repos?

**Comment by YannickJadoul** [comment]
Yeah, the setup for https://github.com/jupyterlab/jupyterlab-demo is a lot more complicated, having an extended [environment.yml](https://github.com/jupyterlab/jupyterlab-demo/blob/master/binder/environment.yml) (which pins down JupyterLab to 0.33.4, but I think I tried this and it didn't matter), and the postBuild script uses a [pyinvoke file for build commands](https://github.com/jupyterlab/jupyterlab-demo/blob/master/tasks.py#L45).

**Comment by choldgraf** [comment]
hmmm, that is curious... @ian-r-rose any idea on why these build errors are popping up all of a sudden?

**Comment by choldgraf** [comment]
or maybe @jasongrout may know?

**Comment by YannickJadoul** [comment]
Update: I don't really know what changed but [my use of extensions](https://github.com/YannickJadoul/Parselmouth/tree/master/binder) on MyBinder [works again](https://mybinder.org/v2/gh/YannickJadoul/Parselmouth/master?urlpath=lab%2Ftree%2Fdocs%2Fexamples). And I just forked this repo, forking MyBinder to not use the previously built image of the master commit, and that seems to work as well: https://mybinder.org/v2/gh/yannickjadoul/jupyterlab/master?urlpath=lab/tree/index.ipynb

So, if you make a commit or can force MyBinder to not reuse the previously built image ... this issue can probably be closed again?

**Comment by choldgraf** [comment]
ahhh interesting, so I guess jupyterlab does some checks periodically and the javascript dependencies got stale. I'll push a commit to rebuild this repo, and hopefully that fixes it! I'll close this issue now, but please do re-open it if the problem persists!
