### ISSUE TITLE
widget not working in mybinder lab

### ISSUE THREAD

**Issue by cornhundred** [binder-examples/jupyterlab#6]
My widget [clustergrammer2](https://github.com/ismms-himc/clustergrammer2) widget works in mybinder [Jupyter Notebook](https://mybinder.org/v2/gh/ismms-himc/clustergrammer2_test/master) but not in mybinder [Jupyter Lab](https://mybinder.org/v2/gh/ismms-himc/clustergrammer2_test/master?urlpath=lab) on mybinder. 

I see the pop-up request for a recommended build

<img width="466" alt="screen shot 2018-11-02 at 5 12 22 pm" src="https://user-images.githubusercontent.com/8352840/47940921-93d48400-dec2-11e8-9948-07f3c7a964ff.png">

But I get a Build Failed error:

Build failed with 504, please run 'jupyter lab build' on the server for full output

and the widget does not render in the `notebooks/introduction_lab.ipynb` notebook.

**Comment by choldgraf** [comment]
argg, I bet we need to re-build this repo because jupyterlab updated its versions...I'll trigger a rebuild now, lemme know if this is still a problem!

**Comment by choldgraf** [comment]
btw, where does clustergrammer come from? Is is a dependency of one of the packages in this repo?

**Comment by cornhundred** [comment]
Hi @choldgraf, clustergrammer is a library that clustergrammer2 (the widget) depends on. These libraries are included in the [clustergrammer2_test](https://github.com/ismms-himc/clustergrammer2_test) repo's [requirements.txt](https://github.com/ismms-himc/clustergrammer2_test/blob/master/requirements.txt). 

I'm using the clustergrammer2_test repo to test the widget on mybinder and I'm still seeing the same build error for Jupyter lab.

#### mybinder notebook link
https://mybinder.org/v2/gh/ismms-himc/clustergrammer2_test/master?filepath=notebooks%2Fintroduction_nb.ipynb

#### mybinder lab link
https://mybinder.org/v2/gh/ismms-himc/clustergrammer2_test/master?urlpath=lab

**Comment by choldgraf** [comment]
ah ok - so this issue isn't specifically for this repo then (binder-examples/jupyterlab)?

Looking into the clustergrammer2 widget, it doesn't seem like it's been made available for lab yet:

https://github.com/MaayanLab/clustergrammer-widget/issues/10

does that look correct to you?

**Comment by cornhundred** [comment]
I'm working on a new widget to replace clustergrammer-widget (https://github.com/maayanlab/clustergrammer-widget), that I'm calling clustergrammer2 (https://github.com/ismms-himc/clustergrammer2). 

Clustergrammer2 works in Jupyter Notebook and Lab locally (I tested pip installing the widget on a few computers and it's working in notebook and lab). However, it only runs on mybinder notebook, but not lab. Sorry for the confusion.

**Comment by choldgraf** [comment]
From your site you mention you must install the widget with

```
jupyter labextension install @jupyter-widgets/jupyterlab-manager
```

but I don't see this in your repository (in a `postBuild` file)...can you try adding this?

**Comment by choldgraf** [comment]
(or whatever other installation commands need to be run to get it working on jupyterlab, make sure you have those run in the binder repository as well)

**Comment by cornhundred** [comment]
Thanks @choldgraf adding the `postBuild` file ([here](https://github.com/ismms-himc/clustergrammer2_test/blob/master/postBuild) next to `requirements.txt`) and making it executable using 

```
chmod +x postBuild
```

worked. 

I'm now able to see the widget in mybinder Jupyter Lab. 

[mybinder lab link](https://mybinder.org/v2/gh/ismms-himc/clustergrammer2_test/master?urlpath=lab)

and 

[mybinder notebook link](https://mybinder.org/v2/gh/ismms-himc/clustergrammer2_test/master?filepath=notebooks%2Fintroduction_nb.ipynb)

Thanks again for your help!

**Comment by choldgraf** [comment]
woot! thanks for your patience in figuring it out!

**Comment by cornhundred** [comment]
Hi @choldgraf, I'm running into the same issue again I believe. 

I raised the issue here https://github.com/jupyter-widgets/ipywidgets/issues/2498. 

Not sure it the issue is appropriate for this repo.

**Comment by choldgraf** [comment]
I'd double check that the version of jupyter lab is the same in both, I know it just had a new version released

**Comment by cornhundred** [comment]
@choldgraf thanks. I was able to fix it and close the issue by releasing a new version of Clustergrammer2. I might have not built the lab extension previously.
